services:
  - type: web
    name: facebook-djezzy-bot
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 index.php"
    envVars:
      - key: PHP_VERSION
        value: "8.1"
